# render.yaml
services:
  - type: web
    name: epiguard
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
